# (PART) Data Exploration and Visualisation

# Introduction {#edav-introduction .unnumbered}

```{r edav-intro-setup}
#| results: asis
#| echo: false
source("_common.R")
status("drafting")
```


Now that we have read our raw data into R we can start getting our data science project moving and being to see some initial returns on the time and effort that we have invested so far. 

In this section we will explore how to wrangle, explore and visualise the data that forms the basis of our projects. These skills are often overlooked by folks coming into data science as being "soft skills" compared to modelling. However, I would argue that this is not the case because each of these tasks requires its own specialist knowledge and tools.

Additionally, these task make up the majority of data scientist's work and are often where we can add the most value to an organisation. At this stage in a project we turn useless, messy data into a form that can be used; we derive initial insights from this data while making minimal assumptions; and we communicate all of this in an accurate and engaging way, to drive decision making both within and outwith the organisation.
