project:
  type: book
  output-dir: _book

book:
  title: "Effective Data Science"
  author: "Zak Varty"
  cover-image: images/EDS-logo.jpg
  #favicon:
  site-url: https://eds-notes.zakvarty.com/
  repo-url: https://github.com/zakvarty/eds-notes-quarto/
  repo-branch: master
  repo-actions: [edit]
  sharing: [twitter, linkedin]
  twitter-card:
    creator: "zakvarty"
  google-analytics: "G-EFK9JPMVM8"
  date: today
  chapters:
    - index.qmd
    - part: 100-workflows-introduction.qmd
      chapters:
        - 101-workflows-organising-your-work.qmd
        - 102-workflows-naming-files.qmd
        - 103-workflows-organising-your-code.qmd
        #- 104-workflows-project-management.qmd
        - 110-workflows-checklist.qmd
    - part: 200-data-introduction.qmd
      chapters:
        - 201-data-tabular.qmd
        - 202-data-webscraping.qmd
        - 203-data-apis.qmd
        #- 204-data-sql.qmd
        - 210-data-checklist.qmd
    - part: 300-edav-intro.qmd
      chapters:
        - 301-edav-wrangling.qmd
        - 302-edav-analysis.qmd
        - 303-edav-visualisation.qmd
        - 310-edav-checklist.qmd
        #- 320-edav-ggplot2-tutorial.qmd
    - part: 400-production-introduction.qmd
      chapters:
        - 401-production-reproducibility.qmd
        - 402-production-explainability.qmd
        - 403-production-scalability.qmd
        - 410-production-checklist.qmd
    - part: 500-ethics-introduction.qmd
      chapters:
        - 501-ethics-privacy.qmd
        - 502-ethics-fairness.qmd
        - 503-ethics-conduct.qmd
        - 510-ethics-checklist.qmd
  appendices:
    - 600-reading-list.qmd
    - 700-references.qmd

bibliography: [packages.bib, references.bib]

format:
  html:
    theme: cosmo
    css: "style.css"
    cover-image: "images/eds-logo.jpg"
    code-link: true
  pdf:
    documentclass: scrreprt
    cover-image: "images/eds-logo.jpg"



