project:
  type: book

book:
  title: "Effective Data Science"
  author: "Zak Varty"
  date: today
  chapters:
    - index.qmd
    - part: 100-workflows-introduction.qmd
    - 101-workflows-organising-your-work.qmd
    - 102-workflows-naming-files.qmd
    - 103-workflows-organising-your-code.qmd
    #- 104-workflows-project-management.qmd
    - 110-workflows-checklist.qmd
    - part: 200-data-introduction.qmd
    - 201-data-tabular.qmd
    - 202-data-webscraping.qmd
    - 203-data-apis.qmd
    #- 204-data-sql.qmd
    - 210-data-checklist.qmd
    - part: 300-edav-intro.qmd
    - 301-edav-wrangling.qmd
    - 302-edav-analysis.qmd
    - 303-edav-visualisation.qmd
    - 310-edav-checklist.qmd
    - part: 400-production-introduction.qmd
    - 401-production-reproducibility.qmd
    - 402-production-explainability.qmd
    - 403-production-scalability.qmd
    - 410-production-checklist.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: "style.css"
    cover-image: "images/eds-logo.jpg"
  pdf:
    documentclass: scrreprt
    cover-image: "images/eds-logo.jpg"



