project:
  type: book

book:
  title: "Effective Data Science"
  author: "Zak Varty"
  date: today
  chapters:
    - index.qmd
    - part: 100-workflows-introduction.qmd
    - 101-workflows-organising-your-work.qmd
    - 102-workflows-naming-files.qmd
    - 103-workflows-organising-your-code.qmd
    #- 104-workflows-project-management.qmd
    - 110-workflows-checklist.qmd
    - part: intro.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: "style.css"
    cover-image: "images/eds-logo.jpg"
  pdf:
    documentclass: scrreprt
    cover-image: "images/eds-logo.jpg"



